export const de = {
  appName: "Heute Admin",
  loading: "Wird geladen …",
  comingSoon: "Bald verfügbar",
  noAccess: "Kein Zugriff",
  noAccessHint:
    "Dieser Bereich ist nur für Administration und Küchenleitung. Bitte melde dich mit einem anderen Konto an.",
  accountDisabled: "Dieses Benutzerkonto ist deaktiviert. Frag bitte an der Rezeption.",
  profileLoadError:
    "Dein Profil konnte nicht geladen werden. Bitte versuche es später erneut oder melde dich ab.",
  login: {
    title: "Anmeldung",
    email: "E-Mail",
    password: "Passwort",
    submit: "Anmelden",
    invalidCredentials:
      "E-Mail oder Passwort stimmt nicht. Bitte prüfe deine Eingabe und versuche es erneut.",
    networkError: "Keine Verbindung. Bitte prüfe dein Netzwerk und versuche es erneut.",
    genericError: "Die Anmeldung hat nicht geklappt. Bitte versuche es später erneut.",
  },
  logout: "Abmelden",
  schedule: {
    previousMonth: "Vorheriger Monat",
    nextMonth: "Nächster Monat",
    date: "Datum",
    weekday: "Wochentag",
    start: "Beginn",
    end: "Ende / 2. Teil",
    remark: "Bemerkung",
    ist: "IST o. Pause",
    totalIst: "IST gesamt",
    totalSoll: "Soll",
    balance: "Saldo",
    empty: "Für diesen Monat gibt es keine aktiven Mitarbeitenden oder keine Dienste.",
    loadError: "Der Dienstplan konnte nicht geladen werden. Bitte versuche es erneut.",
  },
  auditLog: {
    from: "Von",
    to: "Bis",
    table: "Bereich",
    person: "Betroffene Person",
    author: "Autor",
    all: "Alle",
    when: "Zeitpunkt",
    what: "Änderung",
    by: "Autor",
    reason: "Grund",
    before: "Vorher",
    after: "Nachher",
    empty: "Keine Einträge für diese Filter.",
    noChanges: "Keine sichtbaren Felder.",
    system: "System",
    previous: "Zurück",
    next: "Weiter",
    loadError: "Das Änderungsprotokoll konnte nicht geladen werden. Bitte versuche es erneut.",
  },
  nav: {
    overview: "Tagesübersicht",
    schedule: "Dienstplan",
    guests: "Gäste & Verpflegung",
    menu: "Speiseplan",
    housekeeping: "Housekeeping",
    auditLog: "Änderungsprotokoll",
  },
} as const;
