export const de = {
  appName: "Heute Admin",
  loading: "Wird geladen …",
  comingSoon: "Bald verfügbar",
  noAccess: "Kein Zugriff",
  noAccessHint:
    "Dieser Bereich ist nur für Administration und Küchenleitung. Bitte melde dich mit einem anderen Konto an.",
  accountDisabled: "Dieses Benutzerkonto ist deaktiviert. Frag bitte an der Rezeption.",
  profileLoadError:
    "Dein Profil konnte nicht geladen werden. Bitte versuche es später erneut oder melde dich ab.",
  login: {
    title: "Anmeldung",
    email: "E-Mail",
    password: "Passwort",
    submit: "Anmelden",
    invalidCredentials:
      "E-Mail oder Passwort stimmt nicht. Bitte prüfe deine Eingabe und versuche es erneut.",
    networkError: "Keine Verbindung. Bitte prüfe dein Netzwerk und versuche es erneut.",
    genericError: "Die Anmeldung hat nicht geklappt. Bitte versuche es später erneut.",
  },
  logout: "Abmelden",
  schedule: {
    previousMonth: "Vorheriger Monat",
    nextMonth: "Nächster Monat",
    date: "Datum",
    weekday: "Wochentag",
    start: "Beginn",
    end: "Ende / 2. Teil",
    remark: "Bemerkung",
    ist: "IST o. Pause",
    totalIst: "IST gesamt",
    totalSoll: "Soll",
    balance: "Saldo",
    empty: "Für diesen Monat gibt es keine aktiven Mitarbeitenden oder keine Dienste.",
    loadError: "Der Dienstplan konnte nicht geladen werden. Bitte versuche es erneut.",
  },
  shiftDialog: {
    title: "Dienst bearbeiten",
    type: "Art",
    types: {
      normal: "Frühdienst / Spätdienst",
      td: "Teildienst",
      sem: "Seminar",
      urlaub: "Urlaub",
      krank: "Krank",
      frei: "Frei",
    },
    start1: "Beginn",
    end1: "Ende",
    start2: "Beginn 2. Teil",
    end2: "Ende 2. Teil",
    breakMin: "Pause (Min.)",
    note: "Bemerkung",
    reason: "Grund der Änderung (Pflicht)",
    save: "Speichern",
    delete: "Löschen",
    cancel: "Abbrechen",
    reasonRequired: "Bitte einen Grund angeben.",
    invalidRange: "Bitte gültige Zeiten im Format HH:MM angeben (Ende nach Beginn).",
    invalidSecondRange: "Bitte einen gültigen 2. Teil angeben (nach dem 1. Teil, Format HH:MM).",
    invalidBreak: "Die Pause muss eine ganze Zahl zwischen 0 und 240 sein.",
  },
  guests: {
    date: "Datum",
    totalsTitle: "Tagessummen",
    total: "Gesamt",
    veg: "Vegetarisch",
    vegan: "Vegan",
    mos: "MOS",
    note: "Info",
    allergies: "Allergien",
    save: "Speichern",
    saved: "Gespeichert",
    empty: "Für dieses Datum sind keine Gruppen anwesend.",
    loadError: "Die Gäste konnten nicht geladen werden. Bitte versuche es erneut.",
    saveError: "Speichern hat nicht geklappt. Bitte versuche es erneut.",
    meals: { frueh: "Frühstück", mittag: "Mittag", abend: "Abend" },
    errors: {
      invalidNumber: "Bitte ganze Zahlen ab 0 eingeben.",
      dietsExceedTotal: "Vegetarisch, vegan und MOS dürfen nicht höher als die Gesamtzahl sein.",
      noteTooLong: "Die Info darf höchstens 120 Zeichen lang sein.",
      allergyFormat: "Allergien bitte als „gluten 2, milch 1“ eingeben (ganze Zahlen ab 1).",
      allergyUnknown:
        "Unbekannte Allergie. Erlaubt sind z. B. gluten, milch, eier, erdnuesse, sonstige.",
      allergyInvalid: "Die Allergien sind ungültig. Bitte prüfe Namen und Anzahl.",
      duplicate: "Für diese Gruppe, diesen Tag und diese Mahlzeit gibt es bereits einen Eintrag.",
      constraint: "Die Angaben sind nicht zulässig. Bitte prüfe deine Eingabe.",
      forbidden: "Dir fehlt die Berechtigung für diese Änderung.",
    },
  },
  bookings: {
    newGroup: "Neue Gruppe",
    edit: "Bearbeiten",
    delete: "Löschen",
    cancel: "Abbrechen",
    save: "Speichern",
    titleNew: "Neue Gruppe",
    titleEdit: "Gruppe bearbeiten",
    matchcode: "Matchcode",
    label: "Bezeichnung",
    arrival: "Anreise",
    departure: "Abreise",
    note: "Notiz",
    confirmTitle: "Gruppe löschen?",
    confirmText: "Die Gruppe und alle zugehörigen Mahlzeiten werden unwiderruflich gelöscht.",
    confirmDelete: "Endgültig löschen",
    errors: {
      matchcodeRequired: "Bitte gib einen Matchcode an.",
      matchcodeTooLong: "Der Matchcode darf höchstens 40 Zeichen lang sein.",
      labelRequired: "Bitte gib eine Bezeichnung an.",
      labelTooLong: "Die Bezeichnung darf höchstens 120 Zeichen lang sein.",
      invalidDate: "Bitte gib gültige Daten für Anreise und Abreise an.",
      departureBeforeArrival: "Die Abreise darf nicht vor der Anreise liegen.",
      noteTooLong: "Die Notiz darf höchstens 500 Zeichen lang sein.",
    },
  },
  menu: {
    previousWeek: "Vorherige Woche",
    nextWeek: "Nächste Woche",
    week: "Woche ab",
    mittag: "Mittag",
    abend: "Abend",
    mainDish: "Hauptgericht",
    vegVariant: "Vegetarische Variante",
    dessert: "Dessert",
    save: "Speichern",
    saved: "Gespeichert",
    mainDishRequired: "Bitte gib ein Hauptgericht an.",
    empty: "Für diese Woche ist noch kein Speiseplan eingetragen.",
    loadError: "Der Speiseplan konnte nicht geladen werden. Bitte versuche es erneut.",
    forbidden: "Dir fehlt die Berechtigung, den Speiseplan zu ändern.",
    saveError: "Der Eintrag konnte nicht gespeichert werden. Bitte versuche es erneut.",
  },
  auditLog: {
    from: "Von",
    to: "Bis",
    table: "Bereich",
    person: "Betroffene Person",
    author: "Autor",
    all: "Alle",
    when: "Zeitpunkt",
    what: "Änderung",
    by: "Autor",
    reason: "Grund",
    before: "Vorher",
    after: "Nachher",
    empty: "Keine Einträge für diese Filter.",
    noChanges: "Keine sichtbaren Felder.",
    system: "System",
    previous: "Zurück",
    next: "Weiter",
    loadError: "Das Änderungsprotokoll konnte nicht geladen werden. Bitte versuche es erneut.",
  },
  housekeeping: {
    date: "Datum",
    floor: "Etage",
    noFloor: "Ohne Etage (Zonen)",
    room: "Zimmer",
    type: "Art",
    zone: "Bereich",
    assignee: "Zugewiesen an",
    unassigned: "Nicht zugewiesen",
    addTask: "Aufgabe hinzufügen",
    addRoom: "Zimmer hinzufügen",
    deleteTask: "Aufgabe löschen",
    assignError: "Die Zuweisung konnte nicht gespeichert werden. Bitte versuche es erneut.",
    dialog: {
      title: "Aufgabe hinzufügen",
      targetRoom: "Zimmer",
      targetZone: "Bereich",
      target: "Ziel",
      room: "Zimmer",
      zone: "Bereich",
      type: "Art",
      assignee: "Zugewiesen an",
      note: "Notiz",
      reason: "Grund der Änderung (Pflicht)",
      save: "Speichern",
      cancel: "Abbrechen",
      roomRequired: "Bitte wähle ein Zimmer.",
      zoneRequired: "Bitte gib einen Bereich an.",
      reasonRequired: "Bitte einen Grund angeben.",
      invalidTask: "Ungültige Aufgabe: Für dieses Zimmer gibt es an diesem Tag schon eine Aufgabe.",
      invalidAssignee: "Diese Person kann nicht zugewiesen werden.",
      taskDone: "Erledigte Aufgaben können nicht gelöscht werden.",
      saveError: "Die Aufgabe konnte nicht gespeichert werden. Bitte versuche es erneut.",
      confirmTitle: "Aufgabe löschen?",
      confirmText: "Die Aufgabe wird gelöscht. Bitte gib einen Grund an.",
      confirmDelete: "Endgültig löschen",
    },
    roomDialog: {
      title: "Zimmer hinzufügen",
      number: "Zimmernummer",
      floor: "Etage",
      beds: "Betten",
      hasBath: "Mit Bad",
      numberRequired: "Bitte gib eine Zimmernummer an.",
      floorInvalid: "Bitte gib eine gültige Etage an.",
      bedsInvalid: "Bitte gib eine gültige Bettenzahl an.",
      duplicate: "Diese Zimmernummer gibt es schon.",
      saveError: "Das Zimmer konnte nicht gespeichert werden. Bitte versuche es erneut.",
    },
    status: "Status",
    empty: "Für dieses Datum gibt es keine Aufgaben.",
    forbidden: "Dazu fehlt dir die Berechtigung.",
    statusError: "Der Status konnte nicht geändert werden. Bitte versuche es erneut.",
    loadError: "Die Aufgaben konnten nicht geladen werden. Bitte versuche es erneut.",
    types: { abreise: "Abreise", bleiber: "Bleiber" },
    statuses: { offen: "Offen", in_arbeit: "In Arbeit", erledigt: "Erledigt" },
  },
  overview: {
    title: "Heute im Haus",
    team: "Team im Dienst",
    teamEmpty: "Heute ist niemand eingeteilt.",
    teamError: "Das Team konnte nicht geladen werden. Bitte versuche es erneut.",
    meals: "Verpflegung heute",
    mealsEmpty: "Für heute sind keine Mahlzeiten eingetragen.",
    mealsError: "Die Verpflegung konnte nicht geladen werden. Bitte versuche es erneut.",
    cleaning: "Housekeeping",
    cleaningEmpty: "Für heute gibt es keine Aufgaben.",
    cleaningError: "Die Aufgaben konnten nicht geladen werden. Bitte versuche es erneut.",
    progress: "Fortschritt Housekeeping",
    changes: "Letzte Änderungen",
    changesEmpty: "Noch keine Änderungen.",
    changesError: "Die Änderungen konnten nicht geladen werden. Bitte versuche es erneut.",
    departments: {
      kueche: "Küche",
      housekeeping: "Housekeeping",
      bfd: "BFD",
      rezeption: "Rezeption",
    },
    openPage: "Öffnen",
  },
  employees: {
    description:
      "Personal anlegen und ändern. Das Anmeldekonto (E-Mail und Passwort) wird separat angelegt und hier nicht verwaltet.",
    add: "Mitarbeitende hinzufügen",
    edit: "Bearbeiten",
    addTitle: "Mitarbeitende hinzufügen",
    editTitle: "Mitarbeitende bearbeiten",
    name: "Name",
    department: "Abteilung",
    role: "Rolle",
    contract: "Vertrag",
    soll: "Soll (Tag / Monat)",
    sollDay: "Soll pro Tag (HH:MM)",
    sollMonth: "Soll pro Monat (HHH:MM)",
    active: "Aktiv",
    inactive: "Inaktiv",
    status: "Status",
    reason: "Grund der Änderung (Pflicht)",
    reasonRequired: "Bitte einen Grund angeben.",
    invalid: "Bitte Name, Vertrag und Sollzeit prüfen (Format HH:MM).",
    save: "Speichern",
    cancel: "Abbrechen",
    deactivate: "Deaktivieren",
    reactivate: "Reaktivieren",
    deactivateTitle: "Mitarbeitende deaktivieren",
    reactivateTitle: "Mitarbeitende reaktivieren",
    confirm: "Bestätigen",
    empty: "Noch keine Mitarbeitenden.",
    loadError: "Die Mitarbeitenden konnten nicht geladen werden. Bitte versuche es erneut.",
    departments: {
      kueche: "Küche",
      housekeeping: "Housekeeping",
      bfd: "BFD",
      rezeption: "Rezeption",
    },
    roles: { admin: "Admin", kitchen_lead: "Küchenleitung", staff: "Mitarbeitende" },
    contracts: { VZ: "Vollzeit", TZ: "Teilzeit" },
  },
  nav: {
    overview: "Tagesübersicht",
    employees: "Mitarbeiter",
    schedule: "Dienstplan",
    guests: "Gäste & Verpflegung",
    menu: "Speiseplan",
    housekeeping: "Housekeeping",
    auditLog: "Änderungsprotokoll",
  },
} as const;
