export const strings = {
  common: {
    loading: "Wird geladen...",
    retry: "Erneut versuchen",
    undo: "Rückgängig",
    login: "Anmelden",
    stand: "Stand",
    offline: "Offline",
    offlineStand: (time: string) => `Offline – Stand ${time}`,
    lastUpdated: (time: string) => `Stand ${time}`,
    empty: "Keine Daten vorhanden",
    error: "Ein Fehler ist aufgetreten",
    unauthorized: "Nicht angemeldet",
    unauthorizedMessage: "Bitte melde dich an, um fortzufahren.",
    close: "Schließen",
    refresh: "Aktualisieren",
  },
  auth: {
    title: "Heute",
    subtitle: "Jugendherberge Musterberg",
    emailLabel: "E-Mail",
    emailPlaceholder: "name@musterberg.test",
    passwordLabel: "Passwort",
    passwordPlaceholder: "Passwort eingeben",
    showPassword: "Anzeigen",
    hidePassword: "Verbergen",
    showPasswordA11y: "Passwort anzeigen",
    hidePasswordA11y: "Passwort verbergen",
    loginAction: "Anmelden",
    helpText: "Probleme? Frag an der Rezeption.",
    emptyFieldsError: "Bitte gib E-Mail und Passwort ein.",
  },
  profil: {
    title: "Profil",
    nameLabel: "Name",
    roleLabel: "Rolle",
    departmentLabel: "Bereich",
    appVersion: "Version 0.1.0",
    logoutAction: "Abmelden",
    roles: {
      admin: "Admin",
      kitchen_lead: "Küchenleitung",
      staff: "Mitarbeiter",
    },
    departments: {
      kueche: "Küche",
      housekeeping: "Housekeeping",
      bfd: "BFD",
      rezeption: "Rezeption",
    },
  },
  tasks: {
    start: "Starten",
    done: "Fertig",
    reopen: "Wieder öffnen",
    openStatus: "Offen",
    inProgressStatus: "In Arbeit",
    doneStatus: "Erledigt",
    taskDoneUndo: "Aufgabe erledigt",
    title: "Meine Aufgaben",
    completedSection: (count: number) => `Erledigt (${count})`,
    weekdaysShort: ["So", "Mo", "Di", "Mi", "Do", "Fr", "Sa"],
  },
  meals: {
    noLunch: "Kein Mittagessen",
    noDinner: "Kein Abendessen",
    modified: (time: string, prev: number | string) => `Geändert ${time} · vorher ${prev}`,
  },
  kitchen: {
    allergyBanner: "Änderungen vorbehalten – bei Allergien Küchenpersonal fragen",
    emptyDay: "Für diesen Tag sind keine Gäste eingetragen.",
    groupsTitle: "Gruppen",
    menuTitle: "Menü",
    menuNotEntered: "Menü noch nicht eingetragen",
    today: "Heute",
    previousDay: "Vorheriger Tag",
    nextDay: "Nächster Tag",
    dessertPrefix: "Nachspeise",
    vegPrefix: "Veg",
  },
  chips: {
    dienst: "Dienst",
    teildienst: "TD",
    seminar: "SEM",
    abwesend: "Abwesend",
    frei: "Frei",
    veg: "VEG",
    vegan: "vegan",
    mos: "MOS",
    al: "AL",
    lp: "LP",
    gr: "GR",
  },
  tabs: {
    heute: "Heute",
    dienstplan: "Dienstplan",
    team: "Team",
    aufgaben: "Aufgaben",
    kueche: "Küche",
    profil: "Profil",
    comingSoon: "Bald verfügbar",
  },
  team: {
    title: "Team",
    headerTitle: (dateFormatted: string) => `Team · ${dateFormatted}`,
  },
  today: {
    myShift: "Mein Dienst",
    myTasks: "Meine Aufgaben",
    allTasks: "Alle Aufgaben",
    nextPrefix: "Nächste: ",
    guestsToday: "Gäste heute",
    menu: "Menü",
    mittag: "Mittag",
    abend: "Abend",
    frueh: "Früh",
    noShift: "Kein Dienst eingetragen",
    noTasks: "Keine Aufgaben zugewiesen",
    allTasksDone: "Alle Aufgaben erledigt",
    noDinner: "Kein Abendessen",
  },
  shifts: {
    title: "Mein Dienstplan",
    week: "Woche",
    month: "Monat",
    sundayBonus: "(Sonntag)",
    balanceHeader: (ist: string, soll: string) => `IST ${ist} / Soll ${soll} Std.`,
    monthNames: [
      "Januar",
      "Februar",
      "März",
      "April",
      "Mai",
      "Juni",
      "Juli",
      "August",
      "September",
      "Oktober",
      "November",
      "Dezember",
    ],
  },
} as const;

export type Strings = typeof strings;
export default strings;
